// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auth">> = Specific
  const handler = {} as typeof import("../../app/admin/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../app/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings">> = Specific
  const handler = {} as typeof import("../../app/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns">> = Specific
  const handler = {} as typeof import("../../app/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test">> = Specific
  const handler = {} as typeof import("../../app/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trust">> = Specific
  const handler = {} as typeof import("../../app/trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verticals/government/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verticals/government">> = Specific
  const handler = {} as typeof import("../../app/verticals/government/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verticals/healthcare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verticals/healthcare">> = Specific
  const handler = {} as typeof import("../../app/verticals/healthcare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verticals/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verticals/legal">> = Specific
  const handler = {} as typeof import("../../app/verticals/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verticals/property-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verticals/property-management">> = Specific
  const handler = {} as typeof import("../../app/verticals/property-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/voice-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-operations">> = Specific
  const handler = {} as typeof import("../../app/voice-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice">> = Specific
  const handler = {} as typeof import("../../app/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-config">> = Specific
  const handler = {} as typeof import("../../app/api/ai-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-runs/[id]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-runs/[id]/retry">> = Specific
  const handler = {} as typeof import("../../app/api/ai-runs/[id]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-runs/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-runs/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/ai-runs/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/calls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/calls">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/calls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/export">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/performance">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/sentiment-trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/sentiment-trends">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/sentiment-trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/surveys">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/attention/decisions/[id]/override/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attention/decisions/[id]/override">> = Specific
  const handler = {} as typeof import("../../app/api/attention/decisions/[id]/override/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/attention/digests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attention/digests">> = Specific
  const handler = {} as typeof import("../../app/api/attention/digests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/attention/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attention/events">> = Specific
  const handler = {} as typeof import("../../app/api/attention/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/attention/policies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attention/policies">> = Specific
  const handler = {} as typeof import("../../app/api/attention/policies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audio/status/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/status/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/audio/status/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audio/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/audio/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audio/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/upload">> = Specific
  const handler = {} as typeof import("../../app/api/audio/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-logs">> = Specific
  const handler = {} as typeof import("../../app/api/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/debug">> = Specific
  const handler = {} as typeof import("../../app/api/auth/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sso/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sso/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sso/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sso/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sso">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sso/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/unlock">> = Specific
  const handler = {} as typeof import("../../app/api/auth/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/billing/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/invoices">> = Specific
  const handler = {} as typeof import("../../app/api/billing/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/payment-methods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/payment-methods">> = Specific
  const handler = {} as typeof import("../../app/api/billing/payment-methods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/subscription">> = Specific
  const handler = {} as typeof import("../../app/api/billing/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/call-capabilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/call-capabilities">> = Specific
  const handler = {} as typeof import("../../app/api/call-capabilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caller-id/verification-twiml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caller-id/verification-twiml">> = Specific
  const handler = {} as typeof import("../../app/api/caller-id/verification-twiml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caller-id/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caller-id/verify">> = Specific
  const handler = {} as typeof import("../../app/api/caller-id/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/confirmations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/confirmations">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/confirmations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/debug">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/disposition/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/disposition">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/disposition/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/email">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/export">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/notes">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/outcome/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/outcome">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/outcome/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/summary">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/timeline">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/[id]/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/[id]/translate">> = Specific
  const handler = {} as typeof import("../../app/api/calls/[id]/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/recordModulationIntent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/recordModulationIntent">> = Specific
  const handler = {} as typeof import("../../app/api/calls/recordModulationIntent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls">> = Specific
  const handler = {} as typeof import("../../app/api/calls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/start">> = Specific
  const handler = {} as typeof import("../../app/api/calls/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/[id]/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[id]/execute">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/[id]/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/[id]/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[id]/stats">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/[id]/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/troubleshoot-stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/troubleshoot-stream">> = Specific
  const handler = {} as typeof import("../../app/api/chat/troubleshoot-stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/cleanup-recordings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup-recordings">> = Specific
  const handler = {} as typeof import("../../app/api/cron/cleanup-recordings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/fix-orphan-bundles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/fix-orphan-bundles">> = Specific
  const handler = {} as typeof import("../../app/api/cron/fix-orphan-bundles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/health-monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/health-monitor">> = Specific
  const handler = {} as typeof import("../../app/api/cron/health-monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/scheduled-calls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/scheduled-calls">> = Specific
  const handler = {} as typeof import("../../app/api/cron/scheduled-calls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/scheduled-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/scheduled-reports">> = Specific
  const handler = {} as typeof import("../../app/api/cron/scheduled-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/webhook-retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/webhook-retry">> = Specific
  const handler = {} as typeof import("../../app/api/cron/webhook-retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/email-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/email-check">> = Specific
  const handler = {} as typeof import("../../app/api/debug/email-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/env">> = Specific
  const handler = {} as typeof import("../../app/api/debug/env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/run-start-call/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/run-start-call">> = Specific
  const handler = {} as typeof import("../../app/api/debug/run-start-call/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/translation-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/translation-check">> = Specific
  const handler = {} as typeof import("../../app/api/debug/translation-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/errors/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/errors/metrics">> = Specific
  const handler = {} as typeof import("../../app/api/errors/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/evidence/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/verify">> = Specific
  const handler = {} as typeof import("../../app/api/evidence/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/external-entities/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external-entities/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/external-entities/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/external-entities/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external-entities/link">> = Specific
  const handler = {} as typeof import("../../app/api/external-entities/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/external-entities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external-entities">> = Specific
  const handler = {} as typeof import("../../app/api/external-entities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features">> = Specific
  const handler = {} as typeof import("../../app/api/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/auth-adapter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/auth-adapter">> = Specific
  const handler = {} as typeof import("../../app/api/health/auth-adapter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/auth-providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/auth-providers">> = Specific
  const handler = {} as typeof import("../../app/api/health/auth-providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/env">> = Specific
  const handler = {} as typeof import("../../app/api/health/env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/resilience/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/resilience">> = Specific
  const handler = {} as typeof import("../../app/api/health/resilience/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/user">> = Specific
  const handler = {} as typeof import("../../app/api/health/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/[id]/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/[id]/disconnect">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/[id]/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/[id]/sync">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/hubspot/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/hubspot/callback">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/hubspot/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/hubspot/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/hubspot/connect">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/hubspot/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/salesforce/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/salesforce/callback">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/salesforce/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/salesforce/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/salesforce/connect">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/salesforce/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/organizations/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/current">> = Specific
  const handler = {} as typeof import("../../app/api/organizations/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pages-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pages-test">> = Specific
  const handler = {} as typeof import("../../app/api/pages-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rbac/context/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rbac/context">> = Specific
  const handler = {} as typeof import("../../app/api/rbac/context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/realtime/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime/subscribe">> = Specific
  const handler = {} as typeof import("../../app/api/realtime/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recordings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recordings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/recordings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recordings/[key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recordings/[key]">> = Specific
  const handler = {} as typeof import("../../app/api/recordings/[key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reliability/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reliability/webhooks">> = Specific
  const handler = {} as typeof import("../../app/api/reliability/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/[id]/export">> = Specific
  const handler = {} as typeof import("../../app/api/reports/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/schedules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/schedules/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/reports/schedules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/schedules">> = Specific
  const handler = {} as typeof import("../../app/api/reports/schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retention/legal-holds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retention/legal-holds">> = Specific
  const handler = {} as typeof import("../../app/api/retention/legal-holds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retention/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retention">> = Specific
  const handler = {} as typeof import("../../app/api/retention/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rti/digests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rti/digests">> = Specific
  const handler = {} as typeof import("../../app/api/rti/digests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rti/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rti/feed">> = Specific
  const handler = {} as typeof import("../../app/api/rti/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rti/policies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rti/policies">> = Specific
  const handler = {} as typeof import("../../app/api/rti/policies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scorecards/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scorecards/alerts">> = Specific
  const handler = {} as typeof import("../../app/api/scorecards/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scorecards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scorecards">> = Specific
  const handler = {} as typeof import("../../app/api/scorecards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/rebuild/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search/rebuild">> = Specific
  const handler = {} as typeof import("../../app/api/search/rebuild/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopper/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopper/results">> = Specific
  const handler = {} as typeof import("../../app/api/shopper/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopper/scripts/manage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopper/scripts/manage">> = Specific
  const handler = {} as typeof import("../../app/api/shopper/scripts/manage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopper/scripts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopper/scripts">> = Specific
  const handler = {} as typeof import("../../app/api/shopper/scripts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signalwire/numbers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signalwire/numbers">> = Specific
  const handler = {} as typeof import("../../app/api/signalwire/numbers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/survey/ai-results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/survey/ai-results">> = Specific
  const handler = {} as typeof import("../../app/api/survey/ai-results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys">> = Specific
  const handler = {} as typeof import("../../app/api/surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/team/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/invite">> = Specific
  const handler = {} as typeof import("../../app/api/team/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/team/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/members">> = Specific
  const handler = {} as typeof import("../../app/api/team/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-email">> = Specific
  const handler = {} as typeof import("../../app/api/test-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test/e2e/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/e2e">> = Specific
  const handler = {} as typeof import("../../app/api/test/e2e/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tts/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tts/generate">> = Specific
  const handler = {} as typeof import("../../app/api/tts/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage">> = Specific
  const handler = {} as typeof import("../../app/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/[userId]/organization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[userId]/organization">> = Specific
  const handler = {} as typeof import("../../app/api/users/[userId]/organization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/bridge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/bridge">> = Specific
  const handler = {} as typeof import("../../app/api/voice/bridge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/bulk-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/bulk-upload">> = Specific
  const handler = {} as typeof import("../../app/api/voice/bulk-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/call/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/call">> = Specific
  const handler = {} as typeof import("../../app/api/voice/call/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/caller-ids/available/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/caller-ids/available">> = Specific
  const handler = {} as typeof import("../../app/api/voice/caller-ids/available/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/config">> = Specific
  const handler = {} as typeof import("../../app/api/voice/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/config/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/config/test">> = Specific
  const handler = {} as typeof import("../../app/api/voice/config/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/laml/outbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/laml/outbound">> = Specific
  const handler = {} as typeof import("../../app/api/voice/laml/outbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/laml/webrtc-conference/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/laml/webrtc-conference">> = Specific
  const handler = {} as typeof import("../../app/api/voice/laml/webrtc-conference/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/numbers/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/numbers/assign">> = Specific
  const handler = {} as typeof import("../../app/api/voice/numbers/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/numbers/retire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/numbers/retire">> = Specific
  const handler = {} as typeof import("../../app/api/voice/numbers/retire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/numbers/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/numbers/revoke">> = Specific
  const handler = {} as typeof import("../../app/api/voice/numbers/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/script/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/script">> = Specific
  const handler = {} as typeof import("../../app/api/voice/script/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/bridge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/bridge">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/bridge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/outbound-v2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/outbound-v2">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/outbound-v2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/outbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/outbound">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/outbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/shopper/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/shopper">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/shopper/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/survey/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/survey">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/survey/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/translation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/translation">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/translation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/swml/webrtc-conference-v2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/swml/webrtc-conference-v2">> = Specific
  const handler = {} as typeof import("../../app/api/voice/swml/webrtc-conference-v2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/targets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/targets">> = Specific
  const handler = {} as typeof import("../../app/api/voice/targets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/[id]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/[id]/test">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/[id]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/assemblyai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/assemblyai">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/assemblyai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/signalwire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/signalwire">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/signalwire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/subscriptions/[id]/deliveries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/subscriptions/[id]/deliveries">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/subscriptions/[id]/deliveries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/subscriptions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/subscriptions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/subscriptions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/subscriptions/[id]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/subscriptions/[id]/test">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/subscriptions/[id]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/subscriptions">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/survey/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/survey">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/survey/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webrpc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webrpc">> = Specific
  const handler = {} as typeof import("../../app/api/webrpc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webrtc/dial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webrtc/dial">> = Specific
  const handler = {} as typeof import("../../app/api/webrtc/dial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webrtc/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webrtc/session">> = Specific
  const handler = {} as typeof import("../../app/api/webrtc/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
